import Image from 'next/image';import { CheckCircle2, ClipboardList, MessageCircle, PaintBucket } from 'lucide-react';import { Button } from '@/components/ui/Button';import { SectionTitle } from '@/components/ui/SectionTitle';import { professional } from '@/data/professional';import { faqs, portfolio, serviceAreas, testimonials } from '@/data/content';import { services } from '@/data/services';import { PortfolioCard, ServiceCard, TestimonialCard } from './Cards';
export function Hero(){return <section className="bg-gradient-to-br from-slate-950 to-slate-800 py-20 text-white"><div className="container grid items-center gap-10 md:grid-cols-2"><div><p className="font-bold text-amber-400">Pintor autônomo em {professional.cityRegion}</p><h1 className="mt-3 text-4xl font-black md:text-6xl">Pintura profissional para renovar seu ambiente sem complicação.</h1><p className="mt-5 text-lg text-slate-200">{professional.slogan} Atendimento para imóveis residenciais e comerciais.</p><div className="mt-8 flex flex-wrap gap-3"><Button href="/orcamento">Solicitar orçamento</Button><Button href="/portfolio" variant="ghost">Ver trabalhos</Button></div></div><div className="rounded-[2rem] bg-amber-100 p-4 shadow-2xl"><Image src="/images/before-after/antes-depois.svg" alt="Comparativo antes e depois de pintura" width={700} height={520} priority className="rounded-[1.5rem]"/></div></div></section>}
export function TrustIndicators(){return <section className="py-10"><div className="container grid gap-4 md:grid-cols-3">{['Atendimento pelo WhatsApp','Orçamento sem preço inventado','Acabamento limpo e cuidadoso'].map(t=><div key={t} className="rounded-2xl bg-white p-5 font-bold shadow-sm"><CheckCircle2 className="mb-2 text-amber-600"/>{t}</div>)}</div></section>}
export function ServicesSection(){return <section className="py-16"><div className="container"><SectionTitle eyebrow="Serviços" title="Soluções para pintura e acabamento" description="Escolha o serviço ideal e envie os detalhes para uma avaliação responsável."/><div className="grid gap-5 md:grid-cols-3">{services.map(s=><ServiceCard key={s.slug} service={s}/>)}</div></div></section>}
export function BeforeAfterGallery(){return <section className="py-16"><div className="container"><SectionTitle eyebrow="Antes e depois" title="Transformações com preparo e acabamento"/><Image src="/images/before-after/antes-depois.svg" alt="Antes e depois de parede renovada" width={1100} height={520} className="rounded-3xl bg-white shadow" loading="lazy"/></div></section>}
export function ProcessSteps(){const steps=[['Envie os dados',MessageCircle],['Avaliação',ClipboardList],['Execução combinada',PaintBucket]];return <section className="py-16"><div className="container"><SectionTitle eyebrow="Como funciona" title="Atendimento simples do primeiro contato à entrega"/><div className="grid gap-5 md:grid-cols-3">{steps.map(([t,I],i)=>{const Icon=I as typeof MessageCircle;return <div className="rounded-3xl bg-white p-6 shadow-sm" key={String(t)}><Icon className="text-amber-600"/><strong className="mt-4 block text-xl">{i+1}. {String(t)}</strong><p className="mt-2 text-slate-600">As informações são organizadas para entender medidas, estado das paredes, prazo e materiais.</p></div>})}</div></div></section>}
export function CTA(){return <section className="py-16"><div className="container rounded-[2rem] bg-slate-950 p-8 text-white md:p-12"><h2 className="text-3xl font-black">Quer renovar seu imóvel?</h2><p className="mt-3 text-slate-300">Preencha o formulário e receba retorno pelo WhatsApp. Fotos deverão ser enviadas na conversa.</p><Button href="/orcamento" className="mt-6">Começar orçamento</Button></div></section>}
export function PortfolioSection(){return <section className="py-16"><div className="container"><SectionTitle eyebrow="Portfólio" title="Trabalhos realizados"/><div className="grid gap-5 md:grid-cols-3">{portfolio.map(p=><PortfolioCard key={p.title} item={p}/>)}</div></div></section>}
export function AboutPreview(){return <section className="py-16"><div className="container grid gap-8 md:grid-cols-2"><SectionTitle eyebrow="Sobre" title={`${professional.experienceYears} de experiência em pintura`} description="Atendimento próximo, orientação clara sobre materiais e compromisso com a preparação correta das paredes."/><div className="rounded-3xl bg-white p-6 shadow-sm"><p>O objetivo é entregar um serviço organizado, com comunicação direta e acabamento adequado para cada ambiente.</p><Button href="/sobre" variant="secondary" className="mt-5">Conhecer profissional</Button></div></div></section>}
export function Testimonials(){return <section className="py-16"><div className="container"><SectionTitle eyebrow="Depoimentos" title="O que clientes destacam"/><div className="grid gap-5 md:grid-cols-3">{testimonials.map(t=><TestimonialCard key={t.name} item={t}/>)}</div></div></section>}
export function ServiceArea(){return <section className="py-16"><div className="container"><SectionTitle eyebrow="Região" title="Área de atendimento"/><div className="flex flex-wrap gap-3">{serviceAreas.map(a=><span className="rounded-full bg-white px-4 py-2 font-semibold shadow-sm" key={a}>{a}</span>)}</div></div></section>}
export function FAQ(){return <section className="py-16"><div className="container"><SectionTitle eyebrow="Dúvidas" title="Perguntas frequentes"/><div className="grid gap-4">{faqs.map(f=><details key={f.question} className="rounded-2xl bg-white p-5 shadow-sm"><summary className="cursor-pointer font-bold">{f.question}</summary><p className="mt-3 text-slate-600">{f.answer}</p></details>)}</div></div></section>}
